### ISSUE TITLE
New RBAC authentication support?

### ISSUE THREAD

**Issue by mgroves** [imranmomin/Hangfire.Couchbase#23]
Is the new RBAC authentication supported with this extension? I created a user and gave the user permission to a bucket, but I kept getting errors. I used the workaround of creating a user with the same name as the bucket, and now it works. I'm wondering if I'm doing something wrong or maybe this extension doesn't support that yet?

Example of what I'm doing (I'm using ASP.NET Core if that makes any difference):

```
var configuration = new ClientConfiguration
{
    Servers = new List<Uri> { new Uri("http://localhost:8091") },
    BucketConfigs = new Dictionary<string, BucketConfiguration> {
        {"familyPhotos_hangfire", new BucketConfiguration {
            Username = "familyPhotos_hangfire",
            Password = "password",
            BucketName = "familyPhotos_hangfire"
        }}
    }
};
services.AddHangfire(x => x.UseCouchbaseStorage(configuration, "familyPhotos_hangfire"));
```

**Comment by imranmomin** [comment]
@mgroves RBAC is not implemented. Will implement in later end of the year
