### ISSUE TITLE
Storage initialization creates a primary index on bucket

### ISSUE THREAD

**Issue by wspait** [imranmomin/Hangfire.Couchbase#32]
@imranmomin,

Thank you for developing this Couchbase NoSQL storage provider for Hangfire. I work with a team of developers who are currently using this GitHub code through a NuGet package.

We are having issues trying to use this provider in a production scenario. The code in the file **CouchbaseStorage.cs** appears to create a primary index on the bucket specified when configuring and initializing the storage provider. Our database team's standard is not to create or allow creation of primary indexes into the production environment. The reason is that the primary index allows any query to execute, and any query that executes using the Primary index will perform the equivalent of a full database scan. Enabling this in a Production environment is obviously a huge risk.

**CouchbaseStorage.cs**
```csharp
string indexPrefix = $"IDX_{defaultBucket}";
--
IBucket bucket = Client.OpenBucket(Options.DefaultBucket);
{
IBucketManager manager = bucket.CreateManager(bucket.Configuration.Username,   bucket.Configuration.Password);
manager.CreateN1qlPrimaryIndex($"{indexPrefix}_Primary", false); // creates the primary index here; causes issues in production
manager.CreateN1qlIndex($"{indexPrefix}_Type", false, "type");
manager.CreateN1qlIndex($"{indexPrefix}_Id", false, "id");
manager.CreateN1qlIndex($"{indexPrefix}_Expire", false, "expire_on");
manager.CreateN1qlIndex($"{indexPrefix}_Name", false, "name");
}
```

Was this left in the code to allow the different types of queries in the Couchbase storage provider code without having to index each query or field?

Is there a way where this can be removed from the code and indexes can be applied to each query or field accordingly?

Thank you for your time.

**Comment by imranmomin** [comment]
@wspait  - for now there's no flag to disable the primary index. Until I remove the index and apply specific indexes on the query, I would recommend that to create a seperate bucket for hangfire and relax the permission

**Comment by imranmomin** [comment]
@wspait I'm planning to start working on the issue. Any plans or should I simply assign the index to be used for the query

```csharp
List<Counter> rawCounters = context.Query<Counter>()
	.Where(c => c.DocumentType == DocumentTypes.Counter && c.Type == CounterTypes.Raw)
	.UseIndex($"IDX_{defaultBucket}_Type")
	.ToList();
```

Later, I will remove the call to remove the primary index.
