### ISSUE TITLE
Index creation fails silently

### ISSUE THREAD

**Issue by mgroves** [imranmomin/Hangfire.Couchbase#35]
I noticed that if I didn't give enough permission to the RBAC user, that index creation basically fails silently (see lines 101 through 105 here: https://github.com/imranmomin/Hangfire.Couchbase/blob/develop/Hangfire.Couchbase/CouchbaseStorage.cs#L101).

Hangfire then crashes almost immediately because the queries it tries to run aren't indexed. I don't really have a good suggestion of how to deal with this, except maybe throw an exception earlier where index creation fails? Or possibly log that the indexes weren't created? Or both? Or something else? I'm interested in thoughts on this, and I'd be happy to work on a PR to address this.

**Comment by imranmomin** [comment]
Looks like the method handles the exception and returns with the IResult. Can you make the change 

```csharp
IResult result = manager.CreateN1qlPrimaryIndex($"{indexPrefix}_Primary", false);
if (!result.Success) throw result.Exception;
```

Can you check if this will be helpful

**Comment by imranmomin** [comment]
PR - https://github.com/imranmomin/Hangfire.Couchbase/pull/37 raised to fix the issue
