### ISSUE TITLE
Sizing guidelines advice

### ISSUE THREAD

**Issue by mgroves** [imranmomin/Hangfire.Couchbase#38]
I've been using hangfire with couchbase backing for just a small handful of recurring jobs. I'm curious what recommendations / sizing / settings you might use in practice (assuming you've created a separate bucket strictly for Hangfire, as I've done). Do you give it a lot of ram? What type of eviction do you use? Do you use anything like a formula (e.g. I expect X jobs to run in a day, so I allocate X * 100 mb of ram) or a rule of thumb?

**Comment by imranmomin** [comment]
@mgroves Sorry for such a delay response. 

I don't have any preferences on the configuration but below that I usually setup 

1.  Strictly separate bucket for hangfire. As I can freely flush the bucket without any side effects 
2. I usually start with 256 MB and later increase if needed. Though, I haven't increased
3. Full eviction is what is setup
