### ISSUE TITLE
Supported Couchbase version?

### ISSUE THREAD

**Issue by tomap** [imranmomin/Hangfire.Couchbase#7]
Hi,

Which version of couchbase do you support ?
Is there a minimum version?
On which version did you test / use it ?

Thank you

**Comment by imranmomin** [comment]
@tomap I developed using Community Edition 5.0.1 build 5003. But the minimum required for the tool to work is the edition should have Couchbase [N1QL](https://www.couchbase.com/products/n1ql) feature

**Comment by tomap** [comment]
It seems it was introduced in 4.0:
https://developer.couchbase.com/documentation/server/4.0/introduction/whats-new-40.html

We are using 4.5.1 so we should be good

Thank you
