### ISSUE TITLE
Document ID - Prefixing

### ISSUE THREAD

**Issue by bbollard** [imranmomin/Hangfire.Couchbase#8]
Hi, thanks for building this provider, it will really help us out. I reviewed the source and correct me if I am wrong, but I believe your Document ID's are set up as Guids, which is good for uniqueness. Is there any consideration for allowing for a configuration property to set a Prefix onto the document ID? I ask this because we have multiple applications sharing a single CouchBase bucket and as per general practice, we use a application 'prefix' as part of every document ID.

For example, application is `FooBar`, document is `Event 123`, resulting in a document ID of `foobar::event::123`.

Thanks for your consideration.

**Comment by imranmomin** [comment]
@bbollard I will look into.

**Comment by imranmomin** [comment]
@bbollard I have PR for the change requested.. If you can test at your end before I merge

https://github.com/imranmomin/Hangfire.Couchbase/pull/10 - Default document prefix

**Comment by bbollard** [comment]
@imranmomin  initial testing looks good, I see the following documents being created in my CouchBase bucket:

id	hangfire::counter::2e2b64ee-a74d-4571-aa8e-429088209a11
id	hangfire::counter::73c944ec-c149-45e5-aa41-b3ff7b51a469
id	hangfire::job::46f09a83-d4c8-4d5c-881b-cc284708eb15
id	hangfire::job::c90a6b47-f49c-4d5e-aa32-ef427ccbc6af
id	hangifre::lock::c6994341-0a26-4d3e-b592-204e19dadb6e
id	hangifre::lock::cae57379-6c98-45b6-9051-437fe5d2a7e9
id	hangifre::server::6b7e02dd-5c24-46a5-9a55-c5c1af42c726
id	hangifre::state::02487ffc-b73f-458d-af64-dfeaef499985
id	hangifre::state::585d0acf-7ba7-4dc5-8782-ed12521570e7
id	hangifre::state::98e11466-1dfe-4dbb-ac72-4c68902795da
id	hangifre::state::b85ac33e-4646-4492-afb0-491f249bef37
id	hangifre::state::c86b6657-ad1a-44ff-b012-2f58908d8747
id	hangifre::state::de8d78ea-f3a6-4ee6-b017-50c5d1c9b73b

The observation I have is about the Hangfire job ID -- all of the documentation and discussions seem to indicate that although this is a string value, one would expect a GUID as the Job ID. Now, the job ID being returned from an Enqueue request is the Couchbase document ID, such as: 'hangfire::job::46f09a83-d4c8-4d5c-881b-cc284708eb15'

I did see one reference to the statement that the storage engine decides the Job ID, so if that is true the above ID is valid, however I wonder if there is an easy means of just returning the GUID portion of the Job ID. I know string parsing ID's is never a good idea so let's not go there, but is there a way to store the Job ID as a separate element apart from the "Document ID"?  It looks like this feature change may be growing tentacles :)

What are your thoughts here?

Regards,
Brian

**Comment by bbollard** [comment]
The prefix name 'hangfire' is misspelled in several locations. Perhaps you want that portion of the prefix as a global

**Comment by bbollard** [comment]
As a future feature request, the ability to set the appropriate part of the prefix through the GlobalConfiguration UseCouchbsae configuration object would be splendid, that way authors could customize the value based on their own needs, especially if you have multiple products using hangfire in the same Couchbase Bucket.

**Comment by imranmomin** [comment]
yeah.. i notice last week. I have encountered some issue .. so wont be going ahead with the PR

**Comment by imranmomin** [comment]
I won't be going ahead with the changes
